### ISSUE TITLE
list only specific branches

### ISSUE THREAD

**Issue by mickedefault** [calahatras/gitout#60]
for a large project there can be many branches. I think we could do with a more selective filtering than remotes or no remotes.

I think a valid scenario is showing local branches + origin/defaultBranch, i.e. skipping other origin branches that merge in and out from defaultBranch.

**Comment by mickedefault** [comment]
might be easier to exclude them via code, instead of fiddling with the git log command using some combination of  `--not`

**Comment by calahatras** [comment]
Should this be closed as a dupe of #26?
Another filter option would be to show

- Only my branches (as in hide remote branches that have no commits from "me")
- Right click on a branch leaf and exclude it, we should perhaps have a panel somewhere with all branches with options of toggling them visible/hidden

**Comment by mickedefault** [comment]
as long as 26 also handles more advanced filtering :)
I'll add a comment in there and close this one. 👍
